"""
Reference datasets: twelve outside markets, all real, all fetchable without
an account.

Why this module exists
----------------------
`src/data_loader.py` targets the ten datasets originally scoped for this
project. Eight of them are gated (Kaggle auth, Kilts Center academic
registration, a Dataverse WAF) and stay undownloaded rather than faked. That
left the product estimating one market -- UK wholesale gift and homeware --
which is not the market most people asking "should I raise my price?" are
actually in.

This module adds markets that *are* reachable, by pulling from two public
archives that publish data over plain HTTPS with no credentials:

  - Rdatasets (vincentarelbundock/Rdatasets), the CSV mirror of datasets
    shipped with R packages -- which is where the published econometric
    panels live.
  - TidyTuesday (rfordatascience/tidytuesday), a weekly public data project.

How this roster was chosen
--------------------------
Not by hand-picking. Every CSV in both archives plus plotly/datasets --
5,960 files, 64,502,749 rows, 656,584,040 values -- was downloaded and
profiled for a numeric, positive price-like column alongside a numeric,
non-negative quantity-like column (see `python -m src.screen_archives`).
That screen returned 26 candidates, and each was then read against its own
documentation.

Three otherwise-perfect candidates were dropped for being simulated, and are
named here so nobody re-adds them:

  - ISLR/Carseats       "A simulated data set containing sales of child car
                        seats at 400 different stores."
  - Stat2Data/Grocery   "These data are not real, though they are simulated
                        to approximate an actual study."
  - sem/Kmenta          "The endogenous variables P and Q were generated by
                        simulation."

Simulated data would fit beautifully and mean nothing. What survived is
below: twelve datasets with named sources, most of them from published
papers.

Run: python -m src.reference_data
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field
from pathlib import Path

import requests

ROOT = Path(__file__).resolve().parent.parent
REFERENCE_DIR = ROOT / "data" / "csv" / "reference"

RDATASETS = "https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/{pkg}/{item}.csv"
TIDYTUESDAY = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/{path}"


@dataclass
class ReferenceSpec:
    """One outside market, and how to turn its columns into an estimate."""

    key: str
    label: str            # what a shopkeeper would call this market
    filename: str
    url: str
    market: str           # where and when
    source: str           # who published it
    estimator: str        # panel | series | choice
    entity: str = ""      # panel: the column that identifies a product/place
    price: str = ""
    quantity: str = ""
    choice_column: str = ""
    brands: dict = field(default_factory=dict)
    deflator: str = ""    # optional column to divide price by (real prices)
    note: str = ""
    status: str = "not_downloaded"
    row_count: int | None = None
    columns: int | None = None


REFERENCE_DATASETS: list[ReferenceSpec] = [
    # ---------------------------------------------------------------- panels
    ReferenceSpec(
        key="broadway_tickets",
        label="Theatre tickets (Broadway)",
        filename="broadway_grosses.csv",
        url=TIDYTUESDAY.format(path="2020/2020-04-28/grosses.csv"),
        market="1,122 Broadway productions, weekly, June 1985 - March 2020",
        source="Playbill weekly box office grosses, compiled by Alex Cookson for TidyTuesday 2020-04-28",
        estimator="panel",
        entity="show",
        price="avg_ticket_price",
        quantity="seats_sold",
        note=(
            "The largest genuine price/quantity panel in the roster: every show's "
            "average ticket price and seats sold, every week, for 35 years. Shows "
            "discount and surge constantly, so within-show price variation is real "
            "and plentiful."
        ),
    ),
    ReferenceSpec(
        key="cigarettes_us_panel",
        label="Cigarettes (US states, 1963-1992)",
        filename="cigarettes_baltagi.csv",
        url=RDATASETS.format(pkg="Ecdat", item="Cigar"),
        market="46 US states, annual, 1963-1992",
        source="Baltagi & Levin (1992), Structural Change and Economic Dynamics 3:321-335",
        estimator="panel",
        entity="state",
        price="price",
        quantity="sales",
        deflator="cpi",
        note=(
            "The textbook panel-data demand study. Price is deflated by CPI so the "
            "slope is a response to real price, not to thirty years of inflation."
        ),
    ),
    ReferenceSpec(
        key="cigarettes_stock_watson",
        label="Cigarettes (US states, 1985 & 1995)",
        filename="cigarettes_stock_watson.csv",
        url=RDATASETS.format(pkg="AER", item="CigarettesSW"),
        market="48 continental US states, two years, 1985 and 1995",
        source="Stock & Watson (2007), Introduction to Econometrics, 2nd ed.",
        estimator="panel",
        entity="state",
        price="price",
        quantity="packs",
        deflator="cpi",
        note="Two periods per state -- enough to demean, not enough to be precise.",
    ),
    ReferenceSpec(
        key="natural_gas_residential",
        label="Household natural gas",
        filename="natural_gas.csv",
        url=RDATASETS.format(pkg="AER", item="NaturalGas"),
        market="6 US states, annual, 1967-1989",
        source="Baltagi (2002), Econometrics, 3rd ed.",
        estimator="panel",
        entity="state",
        price="price",
        quantity="consumption",
        note=(
            "A utility, and it behaves like one: people cannot easily buy less heat. "
            "The dataset ships no price index, so these are nominal prices across "
            "twenty-two inflationary years -- which is most of why the interval "
            "below is uninformative."
        ),
    ),
    # ------------------------------------------------------------ single series
    ReferenceSpec(
        key="avocados_california",
        label="Avocados (California)",
        filename="avocados_california.csv",
        url=RDATASETS.format(pkg="causaldata", item="avocado"),
        market="California, weekly, 2015-2018, conventional avocados only",
        source="Hass Avocado Board via Kiggins (2018); packaged in causaldata for Huntington-Klein, The Effect",
        estimator="series",
        price="AveragePrice",
        quantity="TotalVolume",
        note=(
            "One market observed over time, so there is no cross-section to demean "
            "against and nothing separates a demand response from a supply glut. "
            "Reported, and flagged, as the weaker design it is."
        ),
    ),
    ReferenceSpec(
        key="rail_freight_1880s",
        label="Rail freight (grain, 1880s)",
        filename="rail_freight_cartel.csv",
        url=RDATASETS.format(pkg="AER", item="CartelStability"),
        market="US Joint Executive Committee railroads, weekly, 1880-1886",
        source="Porter (1983), Bell Journal of Economics 14:301-314",
        estimator="series",
        price="price",
        quantity="quantity",
        note=(
            "Famous precisely because price moved for a reason unrelated to demand: "
            "the cartel collapsed and re-formed repeatedly. That is what makes the "
            "slope readable here and not elsewhere."
        ),
    ),
    # --------------------------------------------------- brand-choice scanner
    ReferenceSpec(
        key="tuna_brands",
        label="Canned tuna",
        filename="tuna_brand_choice.csv",
        url=RDATASETS.format(pkg="Ecdat", item="Tuna"),
        market="US supermarket scanner panel, 13,705 purchase occasions, 5 brands",
        source="Kim, Blattberg & Rossi (1995), Journal of Business & Economic Statistics 13(3):291",
        estimator="choice",
        choice_column="Tuna.choice",
        brands={
            "skw": "price.skw", "cosw": "price.cosw", "pw": "price.pw",
            "sko": "price.sko", "coso": "price.coso",
        },
        note="Five competing tins on one shelf -- the most substitutable category in the roster.",
    ),
    ReferenceSpec(
        key="ketchup_brands",
        label="Ketchup",
        filename="ketchup_brand_choice.csv",
        url=RDATASETS.format(pkg="Ecdat", item="Ketchup"),
        market="US supermarket scanner panel, 4,956 purchase occasions, 4 brands",
        source="Kim, Blattberg & Rossi (1995), Journal of Business & Economic Statistics 13(3):291",
        estimator="choice",
        choice_column="Ketchup.choice",
        brands={
            "heinz": "price.heinz", "hunts": "price.hunts",
            "delmonte": "price.delmonte", "stb": "price.stb",
        },
    ),
    ReferenceSpec(
        key="crackers_brands",
        label="Crackers",
        filename="crackers_brand_choice.csv",
        url=RDATASETS.format(pkg="Ecdat", item="Cracker"),
        market="US supermarket scanner panel, 3,292 purchase occasions, 4 brands",
        source="Jain, Vilcassim & Chintagunta (1994), Journal of Business & Economic Statistics 12(3):317",
        estimator="choice",
        choice_column="choice",
        brands={
            "sunshine": "price.sunshine", "kleebler": "price.kleebler",
            "nabisco": "price.nabisco", "private": "price.private",
        },
    ),
    ReferenceSpec(
        key="catsup_brands",
        label="Catsup (bottle sizes)",
        filename="catsup_brand_choice.csv",
        url=RDATASETS.format(pkg="Ecdat", item="Catsup"),
        market="US supermarket scanner panel, 2,798 purchase occasions, 4 SKUs",
        source="Jain, Vilcassim & Chintagunta (1994), Journal of Business & Economic Statistics 12(3):317",
        estimator="choice",
        choice_column="choice",
        brands={
            "heinz41": "price.heinz41", "heinz32": "price.heinz32",
            "heinz28": "price.heinz28", "hunts32": "price.hunts32",
        },
        note="Three of the four options are the same brand in different sizes.",
    ),
    ReferenceSpec(
        key="yogurt_brands",
        label="Yogurt",
        filename="yogurt_brand_choice.csv",
        url=RDATASETS.format(pkg="Ecdat", item="Yogurt"),
        market="US supermarket scanner panel, 2,412 purchase occasions, 4 brands",
        source="Jain, Vilcassim & Chintagunta (1994), Journal of Business & Economic Statistics 12(3):317",
        estimator="choice",
        choice_column="choice",
        brands={
            "yoplait": "price.yoplait", "dannon": "price.dannon",
            "hiland": "price.hiland", "weight": "price.weight",
        },
    ),
    ReferenceSpec(
        key="orange_juice_brands",
        label="Orange juice",
        filename="orange_juice_choice.csv",
        url=RDATASETS.format(pkg="ISLR", item="OJ"),
        market="US supermarket, 1,070 purchase occasions, 2 brands, 7 stores",
        source="Stine, Foster & Waterman (1998), Business Analysis Using Regression",
        estimator="choice",
        choice_column="Purchase",
        brands={"CH": "SalePriceCH", "MM": "SalePriceMM"},
        note="Only two brands, so a shopper leaving one almost always arrives at the other.",
    ),
]


def download(spec: ReferenceSpec, session: requests.Session | None = None) -> ReferenceSpec:
    """Fetch one dataset. Leaves `status` at not_downloaded on any failure."""
    REFERENCE_DIR.mkdir(parents=True, exist_ok=True)
    out_path = REFERENCE_DIR / spec.filename
    sess = session or requests.Session()

    try:
        resp = sess.get(spec.url, timeout=120)
        resp.raise_for_status()
    except Exception as exc:  # network, DNS, egress policy, 404
        spec.note = (spec.note + " " if spec.note else "") + f"download failed: {exc}"
        return spec

    out_path.write_bytes(resp.content)

    import pandas as pd

    df = pd.read_csv(out_path, low_memory=False)
    spec.status = "downloaded"
    spec.row_count = len(df)
    spec.columns = df.shape[1]
    return spec


def main() -> list[ReferenceSpec]:
    session = requests.Session()
    specs = [download(spec, session) for spec in REFERENCE_DATASETS]

    ok = [s for s in specs if s.status == "downloaded"]
    for s in specs:
        count = f"{s.row_count:,} rows" if s.row_count else "-"
        print(f"  [{s.status:14s}] {s.filename:<32} {count}")
    print(f"\n{len(ok)}/{len(specs)} reference datasets downloaded, "
          f"{sum(s.row_count or 0 for s in ok):,} rows total")
    return specs


if __name__ == "__main__":
    sys.exit(0 if main() else 1)
